### ISSUE TITLE
fails to generate zip on basic docker install

### ISSUE THREAD

**Issue by leonstafford** [WP2Static/static-html-output-plugin#39]
clean WP 5.4.1, WP2Static 6.6.7 from wp.org

 - set permalinks
 - zip deployment; deployment URL: http://localhost:3000

UI shows successful export. 

PHP error log shows:

```
PHP Warning:  rename(/var/www/html/wp-content/uploads/wp-static-html-output-1588621648.tmp,/var/www/html/wp-content/uploads/wp-static-html-output-1588621648.zip): No such file or directory in /var/www/html/wp-content/plugins/static-html-output-plugin/plugin/WP2Static/ArchiveProcessor.php on line 2, referer: http://localhost:8000/wp-admin/admin.php?page=wp2static
```
zip extension appears loaded in wordpress image. issue with tmp path? 

Tested with following docker compose:

```
version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
    db_data: {}

```
